import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final store = Store();
  await store.load();
  runApp(App(store));
}

class Product {
  String id, name, category, barcode, size;
  double price, cost, stock, minStock;
  Product(this.id, this.name, this.category, this.barcode, this.size, this.price, this.cost, this.stock, this.minStock);
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'category':category,'barcode':barcode,'size':size,'price':price,'cost':cost,'stock':stock,'minStock':minStock};
  factory Product.fromJson(Map<String,dynamic> j)=>Product(j['id'],j['name'],j['category'],j['barcode'],j['size'],(j['price'] as num).toDouble(),(j['cost'] as num).toDouble(),(j['stock'] as num).toDouble(),(j['minStock'] as num).toDouble());
}
class Customer {
  String id,name,phone; double debt;
  Customer(this.id,this.name,this.phone,[this.debt=0]);
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'phone':phone,'debt':debt};
  factory Customer.fromJson(Map<String,dynamic> j)=>Customer(j['id'],j['name'],j['phone'],(j['debt'] as num).toDouble());
}
class Sale {
  String invoice,customer; DateTime date; double total,cost; bool credit;
  Sale(this.invoice,this.customer,this.date,this.total,this.cost,this.credit);
  Map<String,dynamic> toJson()=>{'invoice':invoice,'customer':customer,'date':date.toIso8601String(),'total':total,'cost':cost,'credit':credit};
  factory Sale.fromJson(Map<String,dynamic> j)=>Sale(j['invoice'],j['customer'],DateTime.parse(j['date']),(j['total'] as num).toDouble(),(j['cost'] as num).toDouble(),j['credit']);
}
class Expense { String category,note; double amount; DateTime date; Expense(this.category,this.note,this.amount,this.date); Map<String,dynamic> toJson()=>{'category':category,'note':note,'amount':amount,'date':date.toIso8601String()}; factory Expense.fromJson(Map<String,dynamic> j)=>Expense(j['category'],j['note'],(j['amount'] as num).toDouble(),DateTime.parse(j['date'])); }

class Store extends ChangeNotifier {
  final products=<Product>[]; final customers=<Customer>[]; final sales=<Sale>[]; final expenses=<Expense>[]; double creditMarkup=30;
  Future<void> load() async {
    final p=await SharedPreferences.getInstance();
    void read<T>(String key,List<T> list,T Function(Map<String,dynamic>) f){final raw=p.getString(key);if(raw!=null)list.addAll((jsonDecode(raw) as List).map((e)=>f(Map<String,dynamic>.from(e))));}
    read('products',products,Product.fromJson); read('customers',customers,Customer.fromJson); read('sales',sales,Sale.fromJson); read('expenses',expenses,Expense.fromJson);
    if(products.isEmpty){products.addAll([Product('1','طقم حلل ستانلس','أدوات مطبخ','622300000001','10 قطع',1450,1100,8,3),Product('2','كوباية زجاج','زجاج','622300000002','6 قطع',180,120,22,8),Product('3','طبق تقديم','أطباق','622300000003','كبير',95,55,4,5)]);}
    if(customers.isEmpty)customers.add(Customer('1','عميل نقدي',''));
  }
  Future<void> save() async {final p=await SharedPreferences.getInstance();await p.setString('products',jsonEncode(products.map((x)=>x.toJson()).toList()));await p.setString('customers',jsonEncode(customers.map((x)=>x.toJson()).toList()));await p.setString('sales',jsonEncode(sales.map((x)=>x.toJson()).toList()));await p.setString('expenses',jsonEncode(expenses.map((x)=>x.toJson()).toList()));}
  double get stockValue=>products.fold(0,(a,p)=>a+p.stock*p.cost); double get debts=>customers.fold(0,(a,c)=>a+c.debt); double get today=>sales.where((x)=>DateUtils.isSameDay(x.date,DateTime.now())).fold(0,(a,x)=>a+x.total); double get profit=>sales.fold(0,(a,x)=>a+x.total-x.cost)-expenses.fold(0,(a,x)=>a+x.amount);
  void addProduct(Product p){products.add(p);save();notifyListeners();} void addCustomer(Customer c){customers.add(c);save();notifyListeners();} void addExpense(Expense e){expenses.add(e);save();notifyListeners();}
  void sell(Product p,double qty,Customer c,bool credit){if(qty<=0||p.stock<qty)return;final total=p.price*qty*(credit?1.3:1);p.stock-=qty;if(credit)c.debt+=total;sales.add(Sale('DIA-${1001+sales.length}',c.name,DateTime.now(),total,p.cost*qty,credit));save();notifyListeners();}
}

class App extends StatelessWidget {final Store store; const App(this.store,{super.key});@override Widget build(BuildContext c)=>StoreScope(store:store,child:MaterialApp(debugShowCheckedModeBanner:false,title:'الضياء',theme:ThemeData(useMaterial3:true,fontFamily:'Arial',colorSchemeSeed:const Color(0xff176b5b),scaffoldBackgroundColor:const Color(0xfff6f8f7)),home:const Home()));}
class StoreScope extends InheritedNotifier<Store>{const StoreScope({super.key,required Store store,required super.child}):super(notifier:store);static Store of(BuildContext c)=>c.dependOnInheritedWidgetOfExactType<StoreScope>()!.notifier!;}

class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int index=0;final pages=const [Dashboard(),Sales(),Products(),Customers(),More()];@override Widget build(BuildContext c){final wide=MediaQuery.sizeOf(c).width>=900;return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('الضياء',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:()=>showSearch(context:c,delegate:SearchProducts()),icon:const Icon(Icons.search))]),body:Row(children:[if(wide)NavigationRail(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),labelType:NavigationRailLabelType.all,destinations:const [NavigationRailDestination(icon:Icon(Icons.dashboard_outlined),label:Text('الرئيسية')),NavigationRailDestination(icon:Icon(Icons.point_of_sale),label:Text('المبيعات')),NavigationRailDestination(icon:Icon(Icons.inventory_2_outlined),label:Text('المخزون')),NavigationRailDestination(icon:Icon(Icons.people_outline),label:Text('العملاء')),NavigationRailDestination(icon:Icon(Icons.more_horiz),label:Text('المزيد'))]),Expanded(child:pages[index])]),bottomNavigationBar:wide?null:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.point_of_sale),label:'بيع'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),label:'المخزون'),NavigationDestination(icon:Icon(Icons.people_outline),label:'العملاء'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'المزيد')])));}}

class Dashboard extends StatelessWidget{const Dashboard({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return ListView(padding:const EdgeInsets.all(20),children:[Text('لوحة التحكم',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const Text('إدارة معرض الضياء في شاشة واحدة'),const SizedBox(height:18),Wrap(spacing:12,runSpacing:12,children:[Kpi('مبيعات اليوم',s.today,'ج.م',Icons.trending_up),Kpi('صافي الربح',s.profit,'ج.م',Icons.account_balance_wallet),Kpi('قيمة المخزون',s.stockValue,'ج.م',Icons.inventory),Kpi('ديون العملاء',s.debts,'ج.م',Icons.credit_score)]),const SizedBox(height:20),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('تنبيهات المخزون',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...s.products.where((p)=>p.stock<=p.minStock).map((p)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.warning_amber_rounded,color:Colors.orange),title:Text(p.name),subtitle:Text('المتاح ${p.stock.toStringAsFixed(0)} • الحد الأدنى ${p.minStock.toStringAsFixed(0)}')))]))),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const NewSale())),icon:const Icon(Icons.point_of_sale),label:const Text('فاتورة بيع')),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AddProduct())),icon:const Icon(Icons.add_box_outlined),label:const Text('إضافة منتج')),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Scanner())),icon:const Icon(Icons.qr_code_scanner),label:const Text('مسح باركود'))])]);}}
class Kpi extends StatelessWidget{final String title,unit;final double value;final IconData icon;const Kpi(this.title,this.value,this.unit,this.icon,{super.key});@override Widget build(BuildContext c)=>SizedBox(width:245,child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[CircleAvatar(child:Icon(icon)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title),Text('${value.toStringAsFixed(0)} $unit',style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold))]))]))));}

class Sales extends StatelessWidget{const Sales({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return ListView(padding:const EdgeInsets.all(20),children:[Header('المبيعات','الفواتير والمدفوعات',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const NewSale()))),...s.sales.reversed.map((x)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.receipt_long)),title:Text(x.invoice),subtitle:Text('${x.customer} • ${x.date.day}/${x.date.month}/${x.date.year}'),trailing:Text('${x.total.toStringAsFixed(0)} ج.م\n${x.credit?'آجل':'نقدي'}',textAlign:TextAlign.end)))])]);}}
class Products extends StatelessWidget{const Products({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return ListView(padding:const EdgeInsets.all(20),children:[Header('المنتجات','الباركود والمقاسات والمخزون',()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const AddProduct()))),...s.products.map((p)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProductDetails(p))),leading:const CircleAvatar(child:Icon(Icons.inventory_2_outlined)),title:Text(p.name),subtitle:Text('${p.size} • ${p.barcode}'),trailing:Text('${p.stock.toStringAsFixed(0)} قطعة',style:TextStyle(color:p.stock<=p.minStock?Colors.red:Colors.green,fontWeight:FontWeight.bold))))])]);}}
class Customers extends StatelessWidget{const Customers({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return ListView(padding:const EdgeInsets.all(20),children:[Header('العملاء','الأرصدة والمديونيات',()=>showDialog(context:c,builder:(_)=>const CustomerDialog())),...s.customers.map((x)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(x.name),subtitle:Text(x.phone.isEmpty?'بدون هاتف':x.phone),trailing:Text('${x.debt.toStringAsFixed(0)} ج.م',style:TextStyle(color:x.debt>0?Colors.red:Colors.green,fontWeight:FontWeight.bold))))])]);}}
class More extends StatelessWidget{const More({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Text('المزيد',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:12),Tile('المشتريات',Icons.shopping_cart_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Simple('المشتريات')))),Tile('الموردون',Icons.local_shipping_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Simple('الموردون')))),Tile('المصروفات',Icons.payments_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Expenses()))),Tile('التقارير',Icons.bar_chart_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Reports()))),Tile('الإعدادات',Icons.settings_outlined,()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Settings())))]);}
class Header extends StatelessWidget{final String a,b;final VoidCallback add;const Header(this.a,this.b,this.add,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:14),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Text(b)])),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('إضافة'))]));}
class Tile extends StatelessWidget{final String t;final IconData icon;final VoidCallback onTap;const Tile(this.t,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:CircleAvatar(child:Icon(icon)),title:Text(t),trailing:const Icon(Icons.chevron_left)));}

class NewSale extends StatefulWidget{const NewSale({super.key});@override State<NewSale> createState()=>_NewSaleState();}
class _NewSaleState extends State<NewSale>{Product? product;Customer? customer;final q=TextEditingController(text:'1');bool credit=false;@override Widget build(BuildContext c){final s=StoreScope.of(c);customer??=s.customers.first;final total=product==null?0:(product!.price*(double.tryParse(q.text)??1)*(credit?1.3:1));return Scaffold(appBar:AppBar(title:const Text('فاتورة بيع')),body:ListView(padding:const EdgeInsets.all(20),children:[Card(child:ListTile(title:Text(product==null?'اختر المنتج أو امسح الباركود':'${product!.name} — ${product!.size}'),trailing:IconButton(icon:const Icon(Icons.qr_code_scanner),onPressed:()async{final code=await Navigator.push<String>(c,MaterialPageRoute(builder:(_)=>const Scanner()));if(code!=null){final p=s.products.where((x)=>x.barcode==code).firstOrNull;if(p!=null)setState(()=>product=p);}}))),if(product!=null)Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Text('السعر النقدي: ${product!.price.toStringAsFixed(0)} ج.م'),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الكمية')),SwitchListTile(value:credit,onChanged:(v)=>setState(()=>credit=v),title:const Text('بيع آجل (+30%)')),Align(alignment:Alignment.centerRight,child:Text('الإجمالي ${total.toStringAsFixed(0)} ج.م',style:const TextStyle(fontSize:23,fontWeight:FontWeight.bold)))]))),DropdownButtonFormField<Customer>(value:customer,items:s.customers.map((x)=>DropdownMenuItem(value:x,child:Text(x.name))).toList(),onChanged:(v)=>setState(()=>customer=v),decoration:const InputDecoration(labelText:'العميل',border:OutlineInputBorder())),const SizedBox(height:20),FilledButton(onPressed:product==null?null:(){s.sell(product!,double.tryParse(q.text)??1,customer!,credit);Navigator.pop(c);},child:const Padding(padding:EdgeInsets.all(14),child:Text('حفظ الفاتورة')))]));}}

class Scanner extends StatefulWidget{const Scanner({super.key});@override State<Scanner> createState()=>_ScannerState();}
class _ScannerState extends State<Scanner>{bool found=false;@override Widget build(BuildContext c){final desktop=defaultTargetPlatform==TargetPlatform.windows||defaultTargetPlatform==TargetPlatform.linux;return Scaffold(appBar:AppBar(title:const Text('مسح الباركود')),body:desktop?Center(child:Padding(padding:const EdgeInsets.all(24),child:TextField(autofocus:true,decoration:const InputDecoration(labelText:'الباركود',border:OutlineInputBorder()),onSubmitted:(v)=>Navigator.pop(c,v)))):MobileScanner(onDetect:(capture){if(found)return;final value=capture.barcodes.firstOrNull?.rawValue;if(value!=null){found=true;Navigator.pop(c,value);}},overlayBuilder:(c,size)=>Center(child:Container(width:280,height:150,decoration:BoxDecoration(border:Border.all(color:Colors.white,width:3),borderRadius:BorderRadius.circular(16)))));}}

class AddProduct extends StatefulWidget{const AddProduct({super.key});@override State<AddProduct> createState()=>_AddProductState();}
class _AddProductState extends State<AddProduct>{final f=<String,TextEditingController>{for(final x in ['اسم المنتج','التصنيف','المقاس','الباركود','سعر البيع','التكلفة','المخزون','الحد الأدنى'])x:TextEditingController()};@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('إضافة منتج')),body:ListView(padding:const EdgeInsets.all(20),children:[...f.entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:e.value,keyboardType:['سعر البيع','التكلفة','المخزون','الحد الأدنى'].contains(e.key)?TextInputType.number:null,decoration:InputDecoration(labelText:e.key,border:const OutlineInputBorder())))),FilledButton(onPressed:(){if(f['اسم المنتج']!.text.isEmpty||f['الباركود']!.text.isEmpty)return;StoreScope.of(c).addProduct(Product(DateTime.now().microsecondsSinceEpoch.toString(),f['اسم المنتج']!.text,f['التصنيف']!.text.isEmpty?'عام':f['التصنيف']!.text,f['الباركود']!.text,f['المقاس']!.text.isEmpty?'قياسي':f['المقاس']!.text,double.tryParse(f['سعر البيع']!.text)??0,double.tryParse(f['التكلفة']!.text)??0,double.tryParse(f['المخزون']!.text)??0,double.tryParse(f['الحد الأدنى']!.text)??3));Navigator.pop(c);},child:const Text('حفظ المنتج'))]));}
class ProductDetails extends StatelessWidget{final Product p;const ProductDetails(this.p,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(p.name)),body:ListView(padding:const EdgeInsets.all(20),children:[Card(child:ListTile(title:Text(p.name),subtitle:Text('${p.category} • ${p.size}'),trailing:Text(p.barcode))),Wrap(spacing:8,runSpacing:8,children:[Kpi('سعر البيع',p.price,'ج.م',Icons.sell),Kpi('التكلفة',p.cost,'ج.م',Icons.price_check),Kpi('المخزون',p.stock,'قطعة',Icons.inventory),Kpi('قيمة المخزون',p.stock*p.cost,'ج.م',Icons.account_balance_wallet)]),if(p.stock<=p.minStock)const Padding(padding:EdgeInsets.all(12),child:Text('⚠️ المنتج منخفض المخزون',style:TextStyle(color:Colors.red,fontWeight:FontWeight.bold)))]));}
class CustomerDialog extends StatefulWidget{const CustomerDialog({super.key});@override State<CustomerDialog> createState()=>_CustomerDialogState();}class _CustomerDialogState extends State<CustomerDialog>{final n=TextEditingController(),p=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:const Text('إضافة عميل'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'الاسم')),TextField(controller:p,decoration:const InputDecoration(labelText:'الهاتف'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:(){StoreScope.of(c).addCustomer(Customer(DateTime.now().microsecondsSinceEpoch.toString(),n.text,p.text));Navigator.pop(c);},child:const Text('حفظ'))]);}
class Expenses extends StatefulWidget{const Expenses({super.key});@override State<Expenses> createState()=>_ExpensesState();}class _ExpensesState extends State<Expenses>{final a=TextEditingController(),n=TextEditingController(),cat=TextEditingController(text:'عام');@override Widget build(BuildContext c){final s=StoreScope.of(c);return Scaffold(appBar:AppBar(title:const Text('المصروفات')),body:ListView(padding:const EdgeInsets.all(20),children:[...s.expenses.reversed.map((e)=>ListTile(title:Text(e.category),subtitle:Text(e.note),trailing:Text('${e.amount.toStringAsFixed(0)} ج.م'))),TextField(controller:cat,decoration:const InputDecoration(labelText:'التصنيف')),TextField(controller:n,decoration:const InputDecoration(labelText:'الوصف')),TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ')),FilledButton(onPressed:(){s.addExpense(Expense(cat.text,n.text,double.tryParse(a.text)??0,DateTime.now()));setState((){});},child:const Text('إضافة'))]));}}
class Reports extends StatelessWidget{const Reports({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return Scaffold(appBar:AppBar(title:const Text('التقارير')),body:ListView(padding:const EdgeInsets.all(20),children:[Kpi('المبيعات',s.sales.fold(0,(a,x)=>a+x.total),'ج.م',Icons.bar_chart),Kpi('التكلفة',s.sales.fold(0,(a,x)=>a+x.cost),'ج.م',Icons.inventory),Kpi('المصروفات',s.expenses.fold(0,(a,x)=>a+x.amount),'ج.م',Icons.payments),Kpi('صافي الربح',s.profit,'ج.م',Icons.trending_up)]));}}
class Settings extends StatelessWidget{const Settings({super.key});@override Widget build(BuildContext c){final s=StoreScope.of(c);return Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(children:[const ListTile(title:Text('الضياء',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),subtitle:Text('نظام إدارة المبيعات والمخزون')),ListTile(leading:const Icon(Icons.percent),title:const Text('نسبة البيع الآجل'),trailing:Text('${s.creditMarkup.toStringAsFixed(0)}%')),const ListTile(leading:Icon(Icons.currency_exchange),title:Text('العملة'),trailing:Text('ج.م')),const ListTile(leading:Icon(Icons.language),title:Text('اللغة'),trailing:Text('العربية')),const ListTile(leading:Icon(Icons.cloud_outlined),title:Text('السحابة'),subtitle:Text('قاعدة Supabase موجودة في supabase/schema.sql'))]));}}
class Simple extends StatelessWidget{final String title;const Simple(this.title,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Center(child:Text('$title — جاهزة للتوصيل بقاعدة البيانات')));}
class SearchProducts extends SearchDelegate<String>{@override List<Widget>? buildActions(c)=>[IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];@override Widget? buildLeading(c)=>IconButton(onPressed:()=>close(c,''),icon:const Icon(Icons.arrow_back));@override Widget buildResults(c){final s=StoreScope.of(c);return Directionality(textDirection:TextDirection.rtl,child:ListView(children:s.products.where((p)=>p.name.contains(query)||p.barcode.contains(query)).map((p)=>ListTile(title:Text(p.name),subtitle:Text(p.barcode),trailing:Text('${p.stock.toStringAsFixed(0)}')).toList()));}@override Widget buildSuggestions(c)=>buildResults(c);}
extension<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}
